//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cognite.Arb.Integration.Resource.ExternalDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasePerson
    {
        public short CaseNumber { get; set; }
        public Nullable<int> CaseSequence { get; set; }
        public int orgPersonID { get; set; }
        public string RoleInCase { get; set; }
        public System.DateTime LastUpdatedWhen { get; set; }
        public string LastUpdatedBy { get; set; }
        public string CommentsOn { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual RegulationExecutiveUser RegulationExecutiveUser { get; set; }
        public virtual RoleOfPerson RoleOfPerson { get; set; }
        public virtual RegulationExecOrgPersons_Seed RegulationExecOrgPersons_Seed { get; set; }
    }
}
