//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cognite.Arb.Integration.Resource.ExternalDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public Case()
        {
            this.CasePersons = new HashSet<CasePerson>();
        }
    
        public string UserFriendlyDescription { get; set; }
        public short CaseNumber { get; set; }
        public Nullable<bool> IsComplaint { get; set; }
        public Nullable<System.DateTime> OpenedDate { get; set; }
        public string CaseOutcome { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedWhen { get; set; }
        public string CaseManager { get; set; }
        public Nullable<short> LegacyCaseNumber { get; set; }
        public string InitiallyReceivedDocs { get; set; }
        public string InitiallyReceivedDocsFrom { get; set; }
        public string UserComments { get; set; }
        public string StatusSummarised { get; set; }
        public string TypeOfCase { get; set; }
        public string DisplayCaseReference { get; set; }
        public string DisplayLegacyReference { get; set; }
        public Nullable<int> LegacyCaseStatus { get; set; }
        public string PrimaryCaseStatus { get; set; }
        public string SecondaryCaseStatus { get; set; }
        public string WorkflowStatus { get; set; }
        public string WorkflowOutcome { get; set; }
        public string RiskCategory { get; set; }
    
        public virtual ICollection<CasePerson> CasePersons { get; set; }
        public virtual RegulationExecutiveUser RegulationExecutiveUser { get; set; }
    }
}
