//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cognite.Arb.Integration.Resource.ExternalDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExternalDatabaseEntities : DbContext
    {
        public ExternalDatabaseEntities()
            : base("name=ExternalDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CasePerson> CasePersons { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<RegulationExecutivePerson> RegulationExecutivePersons { get; set; }
        public virtual DbSet<RegulationExecutiveUser> RegulationExecutiveUsers { get; set; }
        public virtual DbSet<RoleOfPerson> RoleOfPersons { get; set; }
        public virtual DbSet<NewCas> NewCases { get; set; }
        public virtual DbSet<RegulationExecOrgPersons_Seed> RegulationExecOrgPersons_Seed { get; set; }
    }
}
