USE [ARB_RegulationExecutive]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NewCases](
	[CaseNumber] [smallint] NOT NULL,
 CONSTRAINT [PK_NewCases] PRIMARY KEY CLUSTERED 
(
	[CaseNumber] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TRIGGER [dbo].[LogNewCases] ON [dbo].[Cases] FOR INSERT AS
Begin
INSERT INTO NewCases SELECT CaseNumber FROM inserted
End