//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cognite.Arb.Integration.Resource.ExternalDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewCas
    {
        public short CaseNumber { get; set; }
    }
}
