//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cognite.Arb.Integration.Resource.ExternalDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegulationExecutiveUser
    {
        public RegulationExecutiveUser()
        {
            this.CasePersons = new HashSet<CasePerson>();
            this.Cases = new HashSet<Case>();
            this.RegulationExecutivePersons = new HashSet<RegulationExecutivePerson>();
        }
    
        public string UserNameNT { get; set; }
        public string UserNameFriendly { get; set; }
        public string EmailAddress { get; set; }
        public string JobDescription { get; set; }
        public string UserInitials { get; set; }
    
        public virtual ICollection<CasePerson> CasePersons { get; set; }
        public virtual ICollection<Case> Cases { get; set; }
        public virtual ICollection<RegulationExecutivePerson> RegulationExecutivePersons { get; set; }
    }
}
