//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cognite.Arb.Integration.Resource.ExternalDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegulationExecutivePerson
    {
        public string title { get; set; }
        public int title_id { get; set; }
        public string Forenames { get; set; }
        public string Initials { get; set; }
        public string Surname { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public string Address6 { get; set; }
        public string AddressPostcode { get; set; }
        public string country { get; set; }
        public int country_id { get; set; }
        public string TelBusiness { get; set; }
        public string Telephone { get; set; }
        public string EmailAddress { get; set; }
        public string fax { get; set; }
        public string WebUrl { get; set; }
        public int orgPersonID { get; set; }
        public int RegulationExecutivePersonID { get; set; }
        public string DefaultRole1 { get; set; }
        public string DefaultRole2 { get; set; }
        public string DefaultRole3 { get; set; }
        public string DefaultRole4 { get; set; }
        public string CommentOn { get; set; }
        public System.DateTime LastUpdatedWhen { get; set; }
        public string LastUpdatedBy { get; set; }
        public string InvertedDisplayName { get; set; }
        public string SurnameMetaphKey { get; set; }
        public string ForenamesMetaphKey { get; set; }
    
        public virtual RegulationExecutiveUser RegulationExecutiveUser { get; set; }
        public virtual RoleOfPerson RoleOfPerson { get; set; }
        public virtual RoleOfPerson RoleOfPerson1 { get; set; }
        public virtual RoleOfPerson RoleOfPerson2 { get; set; }
        public virtual RoleOfPerson RoleOfPerson3 { get; set; }
        public virtual RegulationExecOrgPersons_Seed RegulationExecOrgPersons_Seed { get; set; }
    }
}
