//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cognite.Arb.Integration.Resource.ExternalDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegulationExecOrgPersons_Seed
    {
        public RegulationExecOrgPersons_Seed()
        {
            this.CasePersons = new HashSet<CasePerson>();
            this.RegulationExecutivePersons = new HashSet<RegulationExecutivePerson>();
        }
    
        public int orgPersonID { get; set; }
        public string RequestedBy { get; set; }
    
        public virtual ICollection<CasePerson> CasePersons { get; set; }
        public virtual ICollection<RegulationExecutivePerson> RegulationExecutivePersons { get; set; }
    }
}
