//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cognite.Arb.Integration.Resource.ExternalDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleOfPerson
    {
        public RoleOfPerson()
        {
            this.CasePersons = new HashSet<CasePerson>();
            this.RegulationExecutivePersons = new HashSet<RegulationExecutivePerson>();
            this.RegulationExecutivePersons1 = new HashSet<RegulationExecutivePerson>();
            this.RegulationExecutivePersons2 = new HashSet<RegulationExecutivePerson>();
            this.RegulationExecutivePersons3 = new HashSet<RegulationExecutivePerson>();
        }
    
        public string RoleOfPerson1 { get; set; }
        public Nullable<bool> SmallMembership { get; set; }
    
        public virtual ICollection<CasePerson> CasePersons { get; set; }
        public virtual ICollection<RegulationExecutivePerson> RegulationExecutivePersons { get; set; }
        public virtual ICollection<RegulationExecutivePerson> RegulationExecutivePersons1 { get; set; }
        public virtual ICollection<RegulationExecutivePerson> RegulationExecutivePersons2 { get; set; }
        public virtual ICollection<RegulationExecutivePerson> RegulationExecutivePersons3 { get; set; }
    }
}
